export const data = {
    currentDate: "2023-01-01",
    events: [
        {
            _id: "1",
            name: "Bautizos",
            image: "https://p1.pxfuel.com/preview/162/248/958/baptism-christening-candle-flame-royalty-free-thumbnail.jpg",
            date: "2022-12-12",
            description: "Haz que el bautizo de tu hijo sea una celebración única y memorable con nuestra organización profesional, creando momentos llenos de amor y significado.",
            category: "Religioso",
            place: "IIglesia y Salon",
            capacity: 40,
            assistance: 40,
            price: 400000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "2",
            name: "Primeras Comuniones",
            image: "https://th.bing.com/th/id/OIP.hgPGdhPNhcgbsjxBhIzKnAHaLH?rs=1&pid=ImgDetMain",
            date: "2023-08-12",
            description: "Celebra con tu hijo con una fiesta inolvidable, cuidada en cada detalle para hacer de este día una experiencia especial.",
            category: "Religioso",
            place: "Iglesia y Salon",
            capacity: 60,
            price: 600000,
            __v: 0,
            estimate: 60,
            type: "privado",
        },
        {
            _id: "3",
            name: "Confirmaciones",
            image: "https://i1.wp.com/fb.ru/misc/i/gallery/30048/710062.jpg",
            date: "2022-11-02",
            description: "Convierte la ocasión única y solemne, con una organización que garantice un evento emotivo y bien planeado.",
            category: "Religioso",
            place: "Iglesia y Salon",
            capacity: 80,
            price: 800000,
            __v: 0,
            assistance: 80,
            type: "privado",
        },
        {
            _id: "4",
            name: "Matrimonios",
            image: "https://th.bing.com/th/id/OIP.DObINVtGiO9JcI9kyErVXAHaE6?rs=1&pid=ImgDetMain",
            date: "2023-11-02",
            description: "Haz realidad la boda de tus sueños, creando un evento personalizado, elegante y lleno de momentos inolvidables para ti y tus invitados.",
            category: "Religioso",
            place: "Iglesia y Salon",
            capacity: 200,
            estimate: 200,
            price: 20000000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "5",
            name: "Aniversarios",
            image: "https://th.bing.com/th/id/OIP.GOLM4fD9Bu3QK1soZOHdmQHaE8?rs=1&pid=ImgDetMain",
            date: "2022-02-12",
            description: "Celebra tu amor o un logro especial con una fiesta única, organizada a la perfección para que tú solo te concentres en disfrutar.",
            category: "Celebración",
            place: "Salon",
            capacity: 30,
            assistance: 30,
            price: 4000000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "6",
            name: "Fiestas de Quince Años",
            image: "https://th.bing.com/th/id/OIP.5hl0KUxgLPdmY5eRXgHqFgHaE7?rs=1&pid=ImgDetMain",
            date: "2023-02-12",
            description: "Haz que el día de tus 15 años sea espectacular y memorable con una fiesta perfectamente organizada.",
            category: "Celebración",
            place: "Salon",
            capacity: 250,
            estimate: 250,
            price: 25000000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "7",
            name: "Conferencias",
            image: "https://th.bing.com/th/id/OIP.-ZCTufl_Pxl01UqzUFsBNAAAAA?rs=1&pid=ImgDetMain",
            date: "2023-01-22",
            description: "Organiza tu conferencia de forma profesional, con todo lo necesario para que tu mensaje llegue de manera impactante y memorable a tu audiencia.",
            category: "Profesional",
            place: "Salon",
            capacity: 200,
            estimate: 200,
            price: 7000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "8",
            name: "Feria de Emprendimiento",
            image: "https://www.inclusion.gob.ec/wp-content/uploads/2023/05/WhatsApp-Image-2023-05-24-at-4.08.24-PM.jpeg",
            date: "2022-01-22",
            description: "Destaca tu emprendimiento en una feria organizada por expertos, que maximiza tu visibilidad y conecta tu marca con posibles clientes e inversionistas.",
            category: "Empresarial",
            place: "Abierto",
            capacity: 1000,
            assistance: 1000,
            price: 7000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "9",
            name: "Graduaciones",
            image: "https://p0.pikist.com/photos/586/313/little-girl-graduation-school-child-graduate-gown-education-student-childhood-thumbnail.jpg",
            date: "2022-03-01",
            description: "Celebra tu graduación como lo merece, con una organización impecable que resalte tu logro y cree recuerdos inolvidables para ti y tus seres queridos",
            category: "Celebración",
            place: "Salon",
            capacity: 200,
            assistance: 200,
            price: 3000000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "10",
            name: "Cumpleaños",
            image: "https://th.bing.com/th/id/OIP.fg2LWt-yriXpBa1-syTXhQHaE8?rs=1&pid=ImgDetMain",
            date: "2023-03-01",
            description: "Haz que tu cumpleaños sea un evento increíble con una organización que se encargue de todos los detalles, para que solo disfrutes de la fiesta.",
            category: "Celebración",
            place: "Salon",
            capacity: 30,
            price: 500000,
            __v: 0,
            estimate: 30,
            type: "privado",
        },
        {
            _id: "11",
            name: "Todo tipo de despedidas",
            image: "https://th.bing.com/th/id/OIP.SuJjKYXz9fsRtubjA7c2UAHaE6?rs=1&pid=ImgDetMain",
            date: "2023-10-15",
            description: "Despedidas únicas y divertidas, donde cada detalle está pensado para hacer de tu adiós una celebración inolvidable, ya sea laboral, de soltero/a o de viaje.",
            category: "Fiesta",
            place: "Discoteca",
            capacity: 80,
            estimate: 80,
            price: 3000000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "12",
            name: "Propuestas de Matrimonio",
            image: "https://th.bing.com/th/id/R.f07d692f665d6a2b9773dad50cc6f0f6?rik=7Zeqz32B%2buTJCA&riu=http%3a%2f%2fwww.okchicas.com%2fwp-content%2fuploads%2f2015%2f02%2fpropuesta-de-matrimonio-7.jpg&ehk=e6to6NdlBrjOE77CkT32wfiunTZ0pHwwGtgYYzwgoT0%3d&risl=&pid=ImgRaw&r=0",
            date: "2022-11-09",
            description: "Haz tu propuesta de matrimonio, creando el ambiente perfecto para que ese momento sea único e inolvidable.",
            category: "Sorpresa",
            place: "Abierto",
            capacity: 10,
            assistance: 10,
            price: 2000000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "13",
            name: "Fiestas Empresariales",
            image: "https://th.bing.com/th/id/OIP.I2jskzt7jBa8WfYzkS0aiQHaE7?rs=1&pid=ImgDetMain",
            date: "2022-3-11",
            description: "Organiza tu fiesta empresarial con nosotros, creando un evento que motive, celebre y conecte a tu equipo, con diversión y profesionalismo garantizados.",
            category: "Empresarial",
            place: "Salon",
            capacity: 200,
            assistance: 200,
            price: 30000000,
            __v: 0,
            type: "privado",
        },
        {
            _id: "14",
            name: "Campaña de Descuentos",
            image: "https://th.bing.com/th/id/OIP.i_j_V9_P8hjTKxcj98Q_JgHaDr?rs=1&pid=ImgDetMain",
            date: "2023-10-15",
            description: "Aprovecha nuestras ferias de descuentos, creadas para atraer a grandes multitudes en busca de las mejores ofertas, todo organizado con eficiencia.",
            category: "Empresarial",
            place: "Local",
            capacity: 9000,
            estimate: 9000,
            price: 5000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "15",
            name: "Feria Artesanal",
            image: "https://th.bing.com/th/id/OIP.oaztQnaI7aH-v-nBp_G4EAHaE7?rs=1&pid=ImgDetMain",
            date: "2023-10-15",
            description: "Celebra la creatividad y el talento local en una feria artesanal cuidadosamente organizada, donde cada detalle resalta el trabajo de los artesanos.",
            category: "Cultural",
            place: "Abierto",
            capacity: 9000,
            estimate: 9000,
            price: 5000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "16",
            name: "Feria de Libros",
            image: "https://th.bing.com/th/id/R.5ce9df767c3c9d79864903595f153601?rik=IhAQJ25Ay20kpA&pid=ImgRaw&r=0",
            date: "2023-10-15",
            description: "Haz que tu feria de libros sea un evento literario único, donde lectores, autores y editoriales se encuentren para compartir.",
            category: "Cultural",
            place: "Abierto",
            capacity: 9000,
            estimate: 9000,
            price: 5000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "17",
            name: "Conciertos",
            image: "https://colombiavisible.com/wp-content/uploads/2022/11/cuerpodespe-1024x576.jpg",
            date: "2023-10-15",
            description: "Convierte tu concierto en una experiencia épica, con una organización que garantice que cada momento sobre el escenario sea inolvidable.",
            category: "Entretenimiento",
            place: "Estadio",
            capacity: 50000,
            estimate: 50000,
            price: 120000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "18",
            name: "Feria Multi Temática",
            image: "https://cdn0.bodas.com.mx/vendor/0937/3_2/960/jpg/feria_5_150937.jpeg",
            date: "2023-10-15",
            description: "Crea una feria multi temática llena de variedad, donde los asistentes puedan disfrutar de una amplia gama de actividades, productos y entretenimiento.",
            category: "Entretenimiento",
            place: "Abierto",
            capacity: 9000,
            estimate: 9000,
            price: 5000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "19",
            name: "Eventos Deportivos",
            image: "https://th.bing.com/th/id/OIP.ACsN9usjpvIFeoUgAUDJIAHaFS?rs=1&pid=ImgDetMain",
            date: "2023-10-15",
            description: "Organizamos eventos deportivos de alto nivel, desde competencias locales hasta torneos internacionales.",
            category: "Deportiva",
            place: "Abierto",
            capacity: 800,
            estimate: 800,
            price: 15000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "20",
            name: "Feria Gastronómica",
            image: "https://cartonlab.com/wp-content/uploads/2023/04/stand-feria-gastronomica-1.jpg",
            date: "2023-10-15",
            description: "Organiza una feria gastronómica inolvidable, con los mejores sabores locales e internacionales, y una experiencia que atraerá a todos los amantes de la buena comida.",
            category: "Cultural",
            place: "Abierto",
            capacity: 9000,
            estimate: 9000,
            price: 5000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "21",
            name: "Show de Comedia",
            image: "https://www.guatemala.com/fotos/2019/12/Show-gratuito-de-comedia-para-ninos-885x500.jpg",
            date: "2023-10-15",
            description: "Organiza un show de comedia que deje a todos riendo, con un ambiente relajado y divertido, donde el humor sea el centro de la diversión.",
            category: "Entretenimiento",
            place: "Local-Abierto",
            capacity: 9000,
            estimate: 9000,
            price: 5000000,
            __v: 0,
            type: "publico",
        },
        {
            _id: "22",
            name: "Fiestas Municipales",
            image: "https://th.bing.com/th/id/R.ac50097a55ba523bf8a6df4170e8f422?rik=NxO2ctErXEBkVA&pid=ImgRaw&r=0",
            date: "2023-10-15",
            description: "Transforma tu fiesta municipal en un evento que todos disfrutarán, con una organización profesional que cubra todos los aspectos para que sea un éxito rotundo.",
            category: "Cultural",
            place: "Abierto",
            capacity: 100000,
            estimate: 100000,
            price: 900000000,
            __v: 0,
            type: "publico",
        },
    ],
}